### ISSUE TITLE
Example 1 unexpected resulting when processing as JSON-LD 

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/citizenship-vocab#10]
[Example 1](https://digitalbazaar.github.io/citizenship-vocab/#example) from the current draft when processing this with the JSON-LD playground appears to drop some of the terms in the [expanded form](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fcitizenship%2Fv1%22%5D%2C%22id%22%3A%22https%3A%2F%2Fissuer.oidp.uscis.gov%2Fcredentials%2F83627465%22%2C%22type%22%3A%5B%22VerifiableCredential%22%2C%22PermanentResidentCard%22%5D%2C%22issuer%22%3A%22did%3Aexample%3A28394728934792387%22%2C%22issuanceDate%22%3A%222019-12-03T12%3A19%3A52Z%22%2C%22expirationDate%22%3A%222029-12-03T12%3A19%3A52Z%22%2C%22credentialSubject%22%3A%7B%22id%22%3A%22did%3Aexample%3Ab34ca6cd37bbf23%22%2C%22type%22%3A%22Person%22%2C%22givenName%22%3A%22JOHN%22%2C%22familyName%22%3A%22SMITH%22%2C%22gender%22%3A%22Male%22%2C%22image%22%3A%22data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgo...kJggg%3D%3D%22%2C%22residentSince%22%3A%222015-01-01%22%2C%22lprCategory%22%3A%22C09%22%2C%22lprNumber%22%3A%22999-999-999%22%2C%22birthCountry%22%3A%22Bahamas%22%2C%22birthDate%22%3A%221958-07-17%22%2C%22mrzInformation%22%3A%22IAUSA0000007032SRC0000000703%3C%3C2001012M1105108BRA%3C%3C%3C%3C%3C%3C%3C%3C%3C%3C%3C5SPECIMEN%3C%3CTEST%3CVOID%3C%3C%3C%3C%3C%3C%3C%3C%3C%3C%3C%22%7D%7D&frame=%7B%7D&context=%7B%7D) namely all of those in the credential subject.

**Comment by mattcollier** [comment]
@tplooker please see this PR for upcoming changes to the context: https://github.com/digitalbazaar/citizenship-vocab/pull/9

**Comment by tplooker** [comment]
Thanks @mattcollier will do

**Comment by msporny** [comment]
Pushed some changes, this seems to be fixed now. Please re-open if it is not.
