### ISSUE TITLE
Move repo under W3C CCG?

### ISSUE THREAD

**Issue by aniltj** [w3c-ccg/citizenship-vocab#12]
When will this move from the digital bazaar owned repo to the W3C CCG owned repo?

**Comment by davidlehn** [comment]
A template repo was created: https://github.com/w3c-ccg/citizenship-vocab
I'm not sure what the plan or process is to move over though.  Would be nice to keep the history.
cc: @kimdhamilton

**Comment by msporny** [comment]
This has been completed:

https://w3c-ccg.github.io/citizenship-vocab/
