### ISSUE TITLE
remote context redirect broken with recent updates

### ISSUE THREAD

**Issue by kdenhartog** [w3c-ccg/citizenship-vocab#13]
It looks like sometime over the past 24 hours the remote context that's identified by `https://w3id.org/citizenship/v1` and redirects to `https://digitalbazaar.github.io/citizenship-vocab/contexts/citizenship-v1.jsonld` was broken.

Can we get the `https://w3id.org/citizenship/v1` url to redirect to the context in this repo now?

is this something @iherman has to do or can chairs/editors do it?

pinging @msporny @peacekeeper @mavarley @dlongley @w3c-ccg/chairs for visibility

**Comment by msporny** [comment]
Fixed https://github.com/perma-id/w3id.org/commit/2573becc150c9b3579b74f05769183609b288396.
