### ISSUE TITLE
Add a note in the README that v2 context is deprecated

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/citizenship-vocab#33]
I'm unsure how to handle these removed items.  On one hand, the v2 context is linking to them here.  On the other, the term definitions don't exist and these are broken references in the rendered spec.

How about since those terms were somewhat temporary, and there never were anchors for them here, that they be removed as done here, but also add a note in the README that v2 context is deprecated and includes some undefined terms.  (I'm not sure if they should even be listed.)

_Originally posted by @davidlehn in https://github.com/w3c-ccg/citizenship-vocab/pull/32#discussion_r1681175778_

**Comment by davidlehn** [comment]
Fixed in https://github.com/w3c-ccg/citizenship-vocab/commit/29db0bc0811bf374105ee00847ad93197a7fadaf.
